site_name: ASL Book
site_description: "An intelligent textbook on American Sign Language"
site_author: 'Curtis Olufson'
repo_name: 'GitHub Repo'
site_url: 'https://Olufsonc-hub.github.io/asl-book/'
repo_url: 'https://github.com/Olufsonc-hub/asl-book'
edit_uri: 'blob/master/docs'

nav:
  - Home: index.md
  - About ths Site: about.md
  - Course Description: course-description.md
  - Learning Graph:
    - Introduction: learning-graph/index.md
    - Course Description Assessment: learning-graph/course-description-assessment.md
    - Concept List: learning-graph/concept-list.md
    - Concept Taxonomy: learning-graph/concept-taxonomy.md
    - Quality Metrics: learning-graph/quality-metrics.md
    - Taxonomy Distribution: learning-graph/taxonomy-distribution.md
theme:
  name: material
   